# Generated by Django 5.2.1 on 2025-05-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('square_meters', models.FloatField()),
            ],
        ),
    ]
