# Generated by Django 5.2.1 on 2025-05-21 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apartment',
            table='apartment',
        ),
    ]
