# Generated by Django 5.2.1 on 2025-05-21 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparments', '0002_alter_apartment_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='apartment',
        ),
    ]
