# Generated by Django 5.2.1 on 2025-05-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_aparments', '0003_delete_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('square_meters', models.FloatField()),
                ('images', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'apartment',
            },
        ),
    ]
