# Generated by Django 5.2.1 on 2025-05-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparments', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
