# Generated by Django 5.2.1 on 2025-05-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparments', '0005_alter_apartment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
