# Generated by Django 5.2.1 on 2025-05-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparments', '0006_alter_apartment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='images',
            field=models.URLField(max_length=350),
        ),
    ]
