# Generated by Django 5.2.1 on 2025-06-24 04:37

import app_aparments.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparments', '0007_alter_apartment_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='elevator',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='garage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='apartment',
            name='pool',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(validators=[app_aparments.validators.number_greater_than_zero]),
        ),
    ]
