# Generated by Django 5.2.1 on 2025-08-22 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparments', '0008_apartment_elevator_apartment_garage_apartment_pool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AparmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(max_length=300)),
                ('aparment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_aparments.apartment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
