# Generated by Django 5.2.1 on 2025-08-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparments', '0009_aparmentimage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aparmentimage',
            table='apartment_image',
        ),
    ]
