# Generated by Django 5.2.1 on 2025-08-23 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparments', '0010_alter_aparmentimage_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='images',
        ),
        migrations.AlterField(
            model_name='aparmentimage',
            name='aparment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_aparments.apartment'),
        ),
    ]
