# Generated by Django 5.2.1 on 2025-08-27 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparments', '0011_remove_apartment_images_alter_aparmentimage_aparment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AparmentImage',
            new_name='ApartmentImage',
        ),
    ]
