# Generated by Django 5.2.1 on 2025-08-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparments', '0012_rename_aparmentimage_apartmentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='state',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='rent', max_length=10),
        ),
    ]
