# Generated by Django 5.2.1 on 2025-11-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparments', '0013_apartment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='square_meters',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
