# Generated by Django 5.2.1 on 2025-11-11 04:03

import app_aparments.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparments', '0014_alter_apartment_square_meters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[app_aparments.validators.number_greater_than_zero]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='square_meters',
            field=models.FloatField(),
        ),
    ]
