# Generated by Django 5.2.1 on 2025-11-11 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparments', '0015_alter_apartment_price_alter_apartment_square_meters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=7, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(10000000000)]),
        ),
    ]
