# Generated by Django 5.2.1 on 2025-11-11 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparments', '0016_alter_apartment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(10000000000)]),
        ),
    ]
