# Generated by Django 5.2.1 on 2026-01-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_aparments', '0019_alter_apartment_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentimage',
            old_name='aparment',
            new_name='apartment',
        ),
    ]
